DataFrames

In [2]:
import numpy as np
import pandas as pd

In [3]:
## creating dataframe

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [7]:
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [46]:
cols=['name','age','city','salary']
df2=pd.DataFrame(data_list,columns=cols)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and indexing of columns

In [47]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: object

In [49]:
df2[['name','city']]

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new columns

In [50]:
df2['designation']=['doctor','eng','teacher','doctor']
df2

    name  age      city  salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000     teacher
3  Linda   42    London   85000      doctor

Removing Columns

In [51]:
df2.drop('designation',axis=1) #sirf view deta hai

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [52]:
# df2.drop(["city","salary"],axis=1,inplace=True)
df2

    name  age      city  salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000     teacher
3  Linda   42    London   85000      doctor

In [54]:
df2.drop(0,axis=0)

    name  age    city  salary designation
1   Anna   34   Paris   70000         eng
2  Peter   29  Berlin   62000     teacher
3  Linda   42  London   85000      doctor

Selecting row

In [55]:
df2.loc[0]

name               John
age                  28
city           New York
salary            65000
designation      doctor
Name: 0, dtype: object

In [56]:
df2.loc[[0,1]]

   name  age      city  salary designation
0  John   28  New York   65000      doctor
1  Anna   34     Paris   70000         eng

In [57]:
df2.iloc[3]

name            Linda
age                42
city           London
salary          85000
designation    doctor
Name: 3, dtype: object

Selecting subsets of rows and columns

In [58]:
df2.loc[[0,1]][['city','salary']]

       city  salary
0  New York   65000
1     Paris   70000

Conditional selection

In [59]:
df2

    name  age      city  salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000     teacher
3  Linda   42    London   85000      doctor

In [60]:
##wants to see those people whose age is above 30
df2[df2['age']>30]

    name  age    city  salary designation
1   Anna   34   Paris   70000         eng
3  Linda   42  London   85000      doctor

In [68]:
## want only people whose age is greater than 30 and belongs to paris
df2[(df2['age']>30 ) & (df2['city']=='Paris')]

   name  age   city  salary designation
1  Anna   34  Paris   70000         eng